### ISSUE TITLE
每次刷新页面都很慢

### ISSUE THREAD

**Issue by reptileZC** [FuAdmin/fu-admin#10]
每次进入项目都很慢且不一定能进入，应该是vite依赖某些无用的东西，但我调试了还是解决不了
![image](https://github.com/FuAdmin/fu-admin/assets/43779409/3ee0659d-afc9-469a-9c88-971491529379)

**Comment by gnyuan** [comment]
遇到一样的问题。应该是前端的问题。后端接口都很清晰。

**Comment by sevntt** [comment]
同样的问题+1

**Comment by FuAdmin** [comment]
更新最新代码后会解决这个问题
