### ISSUE TITLE
代码生成问题

### ISSUE THREAD

**Issue by zshengtao** [FuAdmin/fu-admin#13]
前段代码生成了，后端代码没有生成。且每次点击生成代码都会刷新页面

**Comment by daiyu0602** [comment]
同问 我也是这个问题

**Comment by tzmj** [comment]
代码生成，表单属性无法输入
![Uploading 5d759441_811609.png…]()

**Comment by tzmj** [comment]
![Uploading 5d759441_811609.png…]()

**Comment by FuAdmin** [comment]
后端代码要设置UTF8，开原版表单属性只支持几个
