### ISSUE TITLE
代码生成后，如果再次修改表单并重新生成代码，admin页面无变化

### ISSUE THREAD

**Issue by okFancy** [FuAdmin/fu-admin#18]
挺好的一个项目，作者应该做推广和宣传，非常实用，特别是代码生成的功能。

使用过程中也发现一个问题：

比如我创建了一个test的项目，abc的项目编码。

操作一(（操作流程： 设计表单-->导出代码-->导出数据库)：代码第一次生成时，生成项目中的列表展示正常。

操作二(（操作流程： 和步骤一的一致）：然后我重新设计表单和字段，前端admin中的页面代码以及页面展示均无变化。

如果需要我可以提供demo和复现视频。

**Comment by FuAdmin** [comment]
现在出Pro版了，更强大的在线开发功能，和更好看的UI，你可以试试
