### ISSUE TITLE
在线体验为啥体验不了呢

### ISSUE THREAD

**Issue by rainbow-calf** [FuAdmin/fu-admin#3]
在线体验体验不了是为啥呢

**Comment by FuAdmin** [comment]
能访问啊  http://175.24.184.165:8080/#/dashboard/analysis
![image](https://user-images.githubusercontent.com/108501535/223309901-dc6dc8ae-00eb-4d27-9073-4b3509c8c922.png)

**Comment by FuAdmin** [comment]
已经修复。
